config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  # root to: "pages#home"

  get '/profile', to: 'pages#profile'

  devise_scope :user do
    # Defines the root path route ("/")
    root "carers#index"

    # get '/carers', to: 'users#index'
    # get '/carers/:id', to: 'users#show', as: 'carer'

    resources :carers, only: %i[index show] do
      resources :requests, only: %i[new create]
      resources :reviews, only: %i[new create]
    end

    resources :requests, only: %i[index show edit update destroy]
    resources :pets
  end

  # resources :pets
  resources :chatrooms, only: %i[show] do
    resources :messages, onlt: %i[create]
  end

  resources :forums, only: %i[index show new create] do
    resources :posts, only: %i[create]
  end

  resources :reviews, only: [:destroy]
end

app/controllers/carers_controller.rb
class CarersController < Devise::SessionsController

  before_action :find_carer, only: %i[show]

  def index
    @carers = User.all.where(carer: true)
    @reviews = Review.all.where(carer_id: @carer)

    # Search
    if params[:query].present?
      params[:show_list] = "true"
      @carers = User.near(params[:query], 200).where(carer: true)
    end

    # Map
    @markers = @carers.geocoded.map do |carer|
      {
        lat: carer.latitude,
        lng: carer.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { carer: carer }),
        marker_html: render_to_string(partial: "marker")
      }
    end


    # VIEW
    respond_to do |format|
      format.html
      format.js   # Render the corresponding JavaScript response
    end

  end

  def show
    @reviews = Review.all.where(carer_id: @carer)
  end

  private

  def find_carer
    @carer = User.where(carer: true).find(params[:id])
  end
end

app/views/carers/_info_window.html.erb
<h6><%= link_to carer_path(carer), style: "text-decoration: none;" do %></h6>
  <div class="review-card-map">
    <div class="review-avatar-info">
      <% if carer.photo.present? %>
        <%= cl_image_tag carer.photo.key, class: "avatar-small" %>
      <% end%>
      <div class="review-avatar-info-text">
        <!-- Raquel's code for avg. rating -->
        <% avg_sum = 0 %>
        <% reviews = Review.all.where(carer_id: carer) %>
          <% reviews.each do |review| %>
            <% avg_sum += review.rating %>
          <% end %>
        <% avg_sum %>
          <% if reviews.count > 0 %>
            <% avg_rating = avg_sum / reviews.count %>
            <p><i class="fa-solid fa-star"></i> <%= avg_rating.round(1)%></p>
          <% else %>
            <p><i class="fa-solid fa-star"></i> 3.0</p>
          <% end %>
        <!---->
      </div>
    </div>
    <div class="review-card-info-map">
      <p><i class="fa-solid fa-user"></i> <%= carer.full_name %>, <%= carer.age %></p>
        <div class="d-flex">
          <p><i class="fa-solid fa-location-dot"></i></p><p><%= carer.address %></p>
        </div>
      <p><i class="fa-solid fa-house"></i> <%= carer.house_type %></p>
    </div>
  </div>
<% end %>

app/views/carers/_list_view.html.erb
  <div class="wrapping-list">
    <div class="head-banner">
      <h1>Find a carer</h1>
    </div>

    <div class="row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: carers_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "City"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div>
      <% carers.each do |carer| %>
        <%= link_to carer_path(carer), style: "text-decoration: none;" do %>
        <div class="card-product">
          <div class="card-product-infos">
            <div class="card-info-img">
              <% if carer.photo.attached? %>
                <%= cl_image_tag carer.photo.key, height: 300, width: 400, crop: :fill, class: "card-product-img" %>
              <% else %>
                <%= image_tag "Will-Smith.jpg", height: 300, width: 400, class: "card-product-img" %>
              <% end %>
            </div>
            <div class="card-info-text">
              <div class= "avg-rating">
              <!-- Raquel's code for avg. rating -->
                <% avg_sum = 0 %>
                <% reviews = Review.all.where(carer_id: carer) %>
                  <% reviews.each do |review| %>
                    <% avg_sum += review.rating %>
                  <% end %>
                <% avg_sum %>
                  <% if reviews.count > 0 %>
                    <% avg_rating = avg_sum / reviews.count %>
                    <p><i class="fa-solid fa-star"></i> <%= avg_rating.round(1)%></p>
                  <% else %>
                    <p><i class="fa-solid fa-star"></i> 3.0</p>
                  <% end %>
                  <!---->
              </div>
              <h6 class="user-text"><i class="fa-solid fa-user"></i> <%= carer.full_name %>, <%= carer.age %></h6>
              <p class="user-text"><i class="fa-solid fa-location-dot"></i> <%= carer.address %></p>
              <p class="user-text"><i class="fa-solid fa-house"></i> <%= carer.house_type %></p>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <button class="tab-button map-view-button btn-two" data-action="click->view-toggle#showMapView">Map View</button>
    <br>
    <br>
    <br>
  </div>

app/views/carers/_map_view.html.erb
<div class="wrapping-map">
    <div class="head-banner">
      <h1>Find a carer</h1>
    </div>
    <div class="map-carers">
      <div style="width: 100%; height: 550px; padding: auto; margin: auto; border-radius: 8px"
        data-controller="map"
        data-map-markers-value="<%= markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
    <button class="tab-button list-view-button btn-two" data-action="click->view-toggle#showListView">List View</button>

</div>

app/views/carers/_marker.html.erb
<%= image_tag "Markers_carers_v8.png", height: 60, width: 60, alt: "Logo" %>

app/views/carers/index.html.erb
<div class="m-3" data-controller="view-toggle" data-view-toggle-show-list-value="<%= params[:show_list] == 'true' %>">
  <div data-view-toggle-target="mapSection">
    <%= render 'map_view', markers: @markers %>
  </div>
  <div data-view-toggle-target="listSection">
    <%= render 'list_view', carers: @carers, reviews: @reviews %>
  </div>
  <!--<div class="list-inline tabs-underlined">
    <p><i class="fa-solid fa-location-dot tab-underlined" data-action="click->view-toggle#showMapView"></i></p>
    <p><i class="fa-solid fa-list-ul tab-underlined" data-action="click->view-toggle#showListView"></i></p>
  </div>-->
</div>

app/views/carers/show.html.erb
<div class="carer-show-main-box">
  <div class="head-banner">
    <h1><%= @carer.full_name %>'s profile</h1>
  </div>
  <div class="profile-card">
    <div class="profile-avatar-info">
      <div>
       <% if @carer.photo.present? %>
        <%= cl_image_tag @carer.photo.key, class: "avatar-profile" %>
      <% end%>
      </div>
      <div>
        <div class="profile-avatar-info-title">
          <p><i class="fa-solid fa-user"></i> <%= @carer.full_name %>, <%= @carer.age %></p>
        </div>
        <div class="show-avatar-info-text">
          <div class="d-flex">
            <p><i class="fa-solid fa-location-dot"></i></p><p><%= @carer.address %></p>
          </div>
          <p><i class="fa-solid fa-house"></i><%= @carer.house_type %></p>
            <% avg_sum = 0 %>
            <% avg_sum %>
            <% @reviews.size %>
              <% @reviews.each do |review| %>
                <% avg_sum += review.rating %>
              <% end %>
            <% avg_sum %>
            <% if @reviews.count > 0 %>
              <% avg_rating = avg_sum / @reviews.count %>
              <p><i class="fa-solid fa-star"></i> <%= avg_rating.round(1)%></p>
            <% else %>
              <p><i class="fa-solid fa-star"></i> 3.0</p>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="bio">
      <p><%= @carer.bio %></p>
    </div>
  </div>
  <div class="profile-buttons">
    <%= link_to 'BOOK THIS CARER', new_carer_request_path(@carer), class: "btn-one" %>
    <%= link_to 'BACK TO SEARCH', carers_path, class: "btn-two" %>
  </div>
  <br>
  <p><strong>Reviews</strong></p>
    <% if @reviews.empty? %>
      <p>This carer has no reviews yet.</p>
    <% else %>
      <% @reviews.each do |review| %>
        <div class="review-card">
           <!--<% if review.user == current_user %>
            <%= link_to review_path(review), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this review?" }, class: 'btn btn-danger btn-sm justify-content-end', style: 'background-color: transparent; border: none; color: black;' do %>
            <i class="delete-symbol fa-solid fa-trash-can justify-content-end"></i>
            <% end %>
          <% end %>-->
            <div class="review-avatar-info">
              <%= cl_image_tag review.user.photo.key, class: "avatar-reviews" %>
              <div class="review-avatar-info-text">
                <p><i class="fa-solid fa-star"></i><%= review.rating %></p>
              </div>
            </div>
                <div class="review-card-info">
                  <p><strong><%= review.user.full_name %></strong></p>
                  <div class="reviews-avatar-date">
                  <p><%= review.created_at.strftime("%d/%m/%Y at %H:%M") %></p>
                  </div>
                  <p class="review-avatar-info-text"><%= review.content %></p>
                </div>
        </div>
      <% end %>
    <% end %>
</div>