config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  # root to: "pages#home"

  get '/profile', to: 'pages#profile'

  devise_scope :user do
    # Defines the root path route ("/")
    root "carers#index"

    # get '/carers', to: 'users#index'
    # get '/carers/:id', to: 'users#show', as: 'carer'

    resources :carers, only: %i[index show] do
      resources :requests, only: %i[new create]
      resources :reviews, only: %i[new create]
    end

    resources :requests, only: %i[index show edit update destroy]
    resources :pets
  end

  # resources :pets
  resources :chatrooms, only: %i[show] do
    resources :messages, onlt: %i[create]
  end

  resources :forums, only: %i[index show new create] do
    resources :posts, only: %i[create]
  end

  resources :reviews, only: [:destroy]
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :requests, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :age, presence: true
  validates :pet_type, presence: true
  # validates :photo, presence: true
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :find_pet, only: %i[show edit update destroy]

  def index
    @pets = current_user.pets
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to profile_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @pet.update(pet_params)
      redirect_to profile_path, flash: { success: 'Details was successfully updated.' }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to profile_path
  end

  private

  def find_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :age, :pet_type, :breed, :medical_cond, :special_needs, :photo)
  end
end

app/views/pets/_form.html.erb
  <div class="rounded-form">
    <%= simple_form_for pet do |f| %>
      <%= f.input :name, label: "Pet's name" %>
      <%= f.input :age %>
      <%= f.input :pet_type, label: "Animal" %>
      <%= f.input :breed %>
      <%= f.input :medical_cond, label: "Medical condition" %>
      <%= f.input :special_needs %>
      <%= f.input :photo, as: :file %>

      <%= f.submit class: 'btn-one', style: 'border: none; background-color: $blue-strong; color: white; text-decoration: none; cursor: pointer; text-transform: uppercase; width: 100%; margin-top: 10px;', value: "SAVE" %>
    <% end %>
    <div class="profile-buttons">
      <%= link_to 'CANCEL', profile_path, class: "btn-two", style: "width: 100%;" %>
    </div>
  </div>

app/views/pets/_pets.html.erb
<% if pets.any? %>
  <% pets.each do |pet| %>
    <div class="pet-profile-card">
      <div class="pet-profile-card-avatar">
        <% if pet.photo.attached? %>
          <%= cl_image_tag pet.photo.key, class: "avatar-medium" %>
        <% else %>
          <%= image_tag "default_pet.png", class: "avatar-medium" %>
        <% end %>
      </div>
      <div class="pet-profile-card-info">
        <strong><%= pet.pet_type %>:</strong> <%= pet.name %>, <%= pet.age %>
        <p><strong>Medical condition?</strong> <%= pet.medical_cond %></p>
        <p><strong>Special needs?</strong> <%= pet.special_needs %></p>
      </div>
      <div class="pet-delete-btn">
        <div>
          <%= button_to edit_pet_path(pet), method: :get, class: 'btn btn-primary btn-sm', style: 'background-color: transparent; border: none; display: inline-block;' do %>
          <i class="fas fa-edit"></i>
          <% end %>
          <%= button_to pet_path(pet), method: :delete, data: { turbo_confirm: 'Are you sure you want to remove this pet?' }, class: 'btn btn-danger btn-sm', style: 'background-color: transparent; border: none; color: black;' do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p> You don't have any pets yet... Please add some</p>
<% end %>
<%#= button_to '', pet_path(@pet), class: "fa-solid fa-trash-can", class: "fa-solid fa-pen-to-square", method: :delete, data: { turbo_confirm: "Are you sure you want to remove this pet?" } %>

app/views/pets/edit.html.erb
<div class="m-3">
  <div class="head-banner">
    <h1>Edit <%= @pet.name %>'s details</h1>
  </div>

  <%= render 'form', pet: @pet %>
</div>

app/views/pets/index.html.erb
<%= render 'pets', pets: current_user.pets %>

app/views/pets/new.html.erb
<div class="m-3">
  <div class="head-banner">
    <h1> Add a pet to your profile </h1>
  </div>

  <%= render 'form', pet: @pet %>
</div>

app/views/pets/show.html.erb
<%= link_to 'Back', profile_path, class: 'btn btn-secondary' %>
<p>Name: <%= @pet.name %></p>
<p>Age: <%= @pet.age %></p>
<p>Animal: <%= @pet.pet_type %></p>
<p>Breed: <%= @pet.breed %></p>
<p>Medical condition? <%= @pet.medical_cond %></p>
<p>Special needs? <%= @pet.special_needs %></p>

<%= link_to 'Edit', edit_pet_path, class: 'btn btn-primary' %>
<%= button_to 'Delete', pet_path(@pet), method: :delete, data: { turbo_confirm: "Are you sure?" } %>