config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  # root to: "pages#home"

  get '/profile', to: 'pages#profile'

  devise_scope :user do
    # Defines the root path route ("/")
    root "carers#index"

    # get '/carers', to: 'users#index'
    # get '/carers/:id', to: 'users#show', as: 'carer'

    resources :carers, only: %i[index show] do
      resources :requests, only: %i[new create]
      resources :reviews, only: %i[new create]
    end

    resources :requests, only: %i[index show edit update destroy]
    resources :pets
  end

  # resources :pets
  resources :chatrooms, only: %i[show] do
    resources :messages, onlt: %i[create]
  end

  resources :forums, only: %i[index show new create] do
    resources :posts, only: %i[create]
  end

  resources :reviews, only: [:destroy]
end

app/views/shared/_head.html.erb
<div class="head head-expand-sm head-light head-lewagon">
  <div class="container-fluid elements-top-head">
    <a class="head-brand" href="/">
      <%= image_tag "carepet_logo_v12.png" %>
    </a>


      <ul class="head-items">
      <% if user_signed_in? %>
        <li class="head-item dropdown">


      <%= content_tag :div, class: "dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false do %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar" %>
        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
            <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
            <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
          </svg>
        <% end %>
      <% end %>


        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="headDropdown">
          <%= link_to "Profile", profile_path, class: "dropdown-item" %>
          <%= link_to "Requests", requests_path, class: "dropdown-item" %>
         <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </li>
      <% else %>
          <%= link_to "Login", new_user_session_path, class: "btn-three" %>
      <% end %>
      </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-light navbar-lewagon">
  <div class="">
    <div class="">
    </div>
    <div class="">
      <ul class="nav-items-out">
          <li><a class="nav-link" href="/carers"><i class="fa-solid fa-magnifying-glass"></i></a></li>
          <li><a class="nav-link" href="/requests"><i class="fa-regular fa-calendar-plus"></i></a></li>
          <li><a class="nav-link" href="/forums"> <i class="fa-regular fa-comments"></i></a></li>
      </ul>
    </div>
  </div>
</div>