config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  # root to: "pages#home"

  get '/profile', to: 'pages#profile'

  devise_scope :user do
    # Defines the root path route ("/")
    root "carers#index"

    # get '/carers', to: 'users#index'
    # get '/carers/:id', to: 'users#show', as: 'carer'

    resources :carers, only: %i[index show] do
      resources :requests, only: %i[new create]
      resources :reviews, only: %i[new create]
    end

    resources :requests, only: %i[index show edit update destroy]
    resources :pets
  end

  # resources :pets
  resources :chatrooms, only: %i[show] do
    resources :messages, onlt: %i[create]
  end

  resources :forums, only: %i[index show new create] do
    resources :posts, only: %i[create]
  end

  resources :reviews, only: [:destroy]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :carer, class_name: 'User', foreign_key: :user_id
  belongs_to :pet
  belongs_to :user

  before_validation :set_default_status
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true, inclusion: { in: ['Pending', 'Rejected', 'Accepted'] }

  private

  def set_default_status
    self.status ||= 'Pending'
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    if current_user.carer?
      @requests = Request.where(carer: current_user)
    else
      @requests = Request.where(pet: current_user.pets)
    end

    @upcoming_requests = @requests.where("end_date >= ?", Date.today).order(end_date: :desc)
    @past_requests = @requests.where("end_date < ?", Date.today).order(end_date: :desc)

    @user_requests = Request.where(user: current_user)
    @user_upcoming_requests = @user_requests.where("end_date >= ?", Date.today).order(end_date: :desc)
    @user_past_requests = @user_requests.where("end_date < ?", Date.today).order(end_date: :desc)

    @user = current_user

    @user_requests_sent = Request.joins(pet: :user).where(users: { id: current_user.id })
    @user_requests_sent_upcoming = @user_requests_sent.where("end_date >= ?", Date.today).order(end_date: :asc)
    @user_requests_sent_past = @user_requests_sent.where("end_date < ?", Date.today).order(end_date: :desc)
  end


  def new
    @carer = User.find(params[:carer_id])
    @request = Request.new
  end

  def create
    @carer = User.find(params[:carer_id])
    @request = Request.new(request_params)
    @request.carer = @carer
    if @request.save
      redirect_to requests_path, notice: 'Request sent successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    if @request.update(request_params)
      flash[:notice] = 'Request was successfully updated.'
      redirect_to requests_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_path, notice: 'Request was successfully deleted.'
  end

  private

  def request_params
    params.require(:request).permit(:status, :start_date, :end_date, :carers_home, :pet_id, :price)
  end
end

app/views/requests/_carer_request_sent.html.erb
<div class="profile-card">
  <div class="profile-avatar-info">
    <div>
      <% if request.user.photo.attached? %>
          <%= cl_image_tag request.user.photo.key, class: "avatar-profile" %>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
          <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
          <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
        </svg>
      <% end %>
    </div>
    <%= turbo_frame_tag "request_#{request.id}" do %>
        <div class="profile-avatar-info-text">
          <p class="carer"><strong>Carer: </strong><%= request.user.full_name %>.</p>
          <p><strong>From: </strong><%= request.start_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>To: </strong><%= request.end_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>Pet: </strong><%= request.pet.pet_type %> - <%= request.pet.name %>.</p>
          <p><strong>Price: </strong>£<%= request.price %>.</p>
          <% if request.status == 'Accepted' %>
            <p class="badge badge-success"><strong>Status: </strong><%= request.status %></p>
          <% elsif request.status == 'Rejected' %>
            <p class="badge badge-danger"><strong>Status: </strong><%= request.status %></p>
          <% else %>
            <p class="badge badge-light"><strong>Status: </strong><%= request.status %></p>
          <% end %>
        </div>
    <% end %>
  </div>
  <div class="profile-buttons">
    <%= button_to "EDIT", edit_request_path(request), method: :get, class: "btn-one", style: "border: none;" %>
    <%= button_to "DELETE", request_path(request), method: :delete, class: "btn-two", data: { turbo_confirm: 'Are you sure you want to delete this booking?' } %>
  </div>
</div>

app/views/requests/_past_request_for_carer.html.erb
<div class="requests-box">
  <div class="profile-card">
    <div class="profile-avatar-info">
      <div>
        <% if request.user.photo.attached? %>
            <%= cl_image_tag request.user.photo.key, class: "avatar-profile" %>
        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
            <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
            <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
          </svg>
        <% end %>
    </div>
      <%= turbo_frame_tag "request_#{request.id}" do %>
        <div class="profile-avatar-info-title">
          <div class="profile-avatar-info-text">
          <p><strong>Carer: </strong><%= request.user.full_name %>.</p>
          <p><strong>From: </strong><%= request.start_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>To: </strong><%= request.end_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>Pet: </strong><%= request.pet.pet_type %> - <%= request.pet.name %>.</p>
          <p><strong>Price: </strong>$<%= request.price %>.</p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="profile-buttons">
        <%= link_to "Give a review to " + request.user.full_name, new_carer_review_path(request.user), class: "btn-two" %>
    </div>
</div>

app/views/requests/_past_request_for_pet_owner.html.erb
<div class="requests-box">
  <div class="profile-card">
    <div class="profile-avatar-info">
      <div>
        <% if request.user.photo.attached? %>
            <%= cl_image_tag request.user.photo.key, class: "avatar-profile" %>
        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
            <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
            <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
          </svg>
        <% end %>
      </div>
      <%= turbo_frame_tag "request_#{request.id}" do %>

        <div class="profile-avatar-info-title">
          <div class="profile-avatar-info-text">
            <p><strong>Carer: </strong><%= request.user.full_name %></p>
            <p><strong>From: </strong><%= request.start_date.strftime("%d/%m/%Y") %></p>
            <p><strong>To: </strong><%= request.end_date.strftime("%d/%m/%Y") %></p>
            <p><strong>Pet: </strong><%= request.pet.pet_type %> - <%= request.pet.name %>.</p>
            <p><strong>Price: </strong>$<%= request.price %>.</p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="profile-buttons">
      <%= link_to "Give a review to #{request.user.full_name}", new_carer_review_path(request.user), class: "btn-two" %>
    </div>
</div>

app/views/requests/_request_for_carer.html.erb
<div class="profile-card">
  <div class="profile-avatar-info">
    <div>
      <% if request.carer.photo.attached? %>
          <%= cl_image_tag request.pet.user.photo.key, class: "avatar-profile" %>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
          <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
          <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
        </svg>
      <% end %>
    </div>
    <%= turbo_frame_tag "request_#{request.id}" do %>
      <div class="profile-avatar-info-title">
          <p>$ <%= request.price %></p>
        <div class="profile-avatar-info-text">
        <p><i class="fa-solid fa-user"></i> <%= request.pet.user.full_name %></p>
          <p><%= request.start_date.strftime("%d/%m/%Y") %></p>
          <p><%= request.end_date.strftime("%d/%m/%Y") %></p>
          <p><%= request.pet.pet_type %>: <%= request.pet.name %></p>
          <p><%= request.status %></p>
        </div>
      </div>
    <% end %>
  </div>

    <div class="profile-buttons">
        <%= button_to "ACCEPT", request_path(request, request: { status: 'Accepted'}), method: :patch, class: "btn-one", style: "border: none;" %>
        <%= button_to "REJECT", request_path(request, request: { status: 'Rejected'}), method: :patch, class: "btn-two", data: { turbo_confirm: 'Are you sure you want to reject this booking?' } %>
    </div>
</div>

app/views/requests/_request_for_pet_owner.html.erb
<div class="profile-card">
  <div class="profile-avatar-info">
    <div>
      <% if request.carer.photo.attached? %>
          <%= cl_image_tag request.carer.photo.key, class: "avatar-profile" %>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
          <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
          <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
        </svg>
      <% end %>
    </div>
    <%= turbo_frame_tag "request_#{request.id}" do %>

      <div class="profile-avatar-info-title">
          <p>$ <%= request.price %></p>
        <div class="profile-avatar-info-text">
        <p><i class="fa-solid fa-user"></i> <%= request.carer.full_name %></p>
          <p>From: <%= request.start_date.strftime("%d/%m/%Y") %></p>
          <p>to: <%= request.end_date.strftime("%d/%m/%Y") %></p>
          <p>Pet: <%= request.pet.name %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="profile-buttons">
    <%= button_to "EDIT", edit_request_path(request), method: :get, class: "btn-one", style: "border: none;" %>
    <%= button_to "DELETE", requests_path, method: :delete, class: "btn-two", data: { turbo_confirm: 'Are you sure you want to delete this booking?' } %>
  </div>
</div>

app/views/requests/_upcoming_request_for_carer.html copy.erb
<div class="profile-card">
  <div class="profile-avatar-info">
    <div>
      <% if request.carer.photo.attached? %>
          <%= cl_image_tag request.pet.user.photo.key, class: "avatar-profile" %>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
          <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
          <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
        </svg>
      <% end %>
    </div>
    <%= turbo_frame_tag "request_#{request.id}" do %>
      <div class="profile-avatar-info-title">
        <div class="profile-avatar-info-text">
        <p><i class="fa-solid fa-user"></i> <%= request.pet.user.full_name %></p>
          <p><strong>From: </strong><%= request.start_date.strftime("%d/%m/%Y") %></p>
          <p><strong>To: </strong><%= request.end_date.strftime("%d/%m/%Y") %></p>
          <p><strong>Pet: </strong><%= request.pet.pet_type %>, Name: <%= request.pet.name %></p>
          <p><strong>Price: </strong>$<%= request.price %></p>
          <% if request.status == 'Accepted' %>
            <p class="badge badge-success"><strong>Status: </strong><%= request.status %></p>
          <% elsif request.status == 'Rejected' %>
            <p class="badge badge-danger"><strong>Status: </strong><%= request.status %></p>
          <% else %>
            <p class="badge badge-light"><strong>Status: </strong><%= request.status %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

    <div class="profile-buttons" data-controller='disable-btn'>
      <%= link_to "ACCEPT", request_path(request, request: { status: 'Accepted'}), data: { turbo_method: :patch, disable_btn_target: 'btn', action: 'click->disable-btn#disable' }, class: "btn-one", style: "border: none;" %>
      <%= link_to "REJECT", request_path(request, request: { status: 'Rejected'}), data: { turbo_method: :patch, turbo_confirm: 'Are you sure you want to reject this booking?', disable_btn_target: 'btn', action: 'click->disable-btn#disable' }, class: "btn-two" %>
    </div>
</div>

app/views/requests/_upcoming_request_for_carer.html.erb
<div class="profile-card">
  <div class="profile-avatar-info">
    <div>
      <% if request.carer.photo.attached? %>
          <%= cl_image_tag request.pet.user.photo.key, class: "avatar-profile" %>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
          <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
          <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
        </svg>
      <% end %>
    </div>
    <%= turbo_frame_tag "request_#{request.id}" do %>
      <div class="profile-avatar-info-title">
        <div class="profile-avatar-info-text">
          <p><strong>Carer: </strong><%= request.pet.user.full_name %>.</p>
          <p><strong>From: </strong><%= request.start_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>To: </strong><%= request.end_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>Pet: </strong><%= request.pet.pet_type %> - <%= request.pet.name %>.</p>
          <p><strong>Price: </strong>$<%= request.price %>.</p>
          <% if request.status == 'Accepted' %>
            <p class="badge badge-success"><strong>Status: </strong><%= request.status %></p>
          <% elsif request.status == 'Rejected' %>
            <p class="badge badge-danger"><strong>Status: </strong><%= request.status %></p>
          <% else %>
            <p class="badge badge-light"><strong>Status: </strong><%= request.status %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

    <div class="profile-buttons" data-controller='disable-btn'>
      <%= link_to "ACCEPT", request_path(request, request: { status: 'Accepted'}), data: { turbo_method: :patch, disable_btn_target: 'btn', action: 'click->disable-btn#disable' }, class: "btn-one", style: "border: none;" %>
      <%= link_to "REJECT", request_path(request, request: { status: 'Rejected'}), data: { turbo_method: :patch, turbo_confirm: 'Are you sure you want to reject this booking?', disable_btn_target: 'btn', action: 'click->disable-btn#disable' }, class: "btn-two" %>
    </div>
</div>

app/views/requests/_upcoming_request_for_pet_owner.html.erb
<div class="profile-card">
  <div class="profile-avatar-info">
    <div>
      <% if request.carer.photo.attached? %>
          <%= cl_image_tag request.carer.photo.key, class: "avatar-profile" %>
      <% else %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
          <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
          <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
        </svg>
      <% end %>
    </div>
    <%= turbo_frame_tag "request_#{request.id}" do %>

      <div class="profile-avatar-info-title">
        <div class="profile-avatar-info-text">
          <p><strong>Carer: </strong><%= request.carer.full_name %>.</p>
          <p><strong>From: </strong><%= request.start_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>To: </strong><%= request.end_date.strftime("%d/%m/%Y") %>.</p>
          <p><strong>Pet: </strong><%= request.pet.pet_type %> - <%= request.pet.name %>.</p>
          <p><strong>Price: </strong>$<%= request.price %>.</p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="profile-buttons">
    <%= button_to "EDIT", edit_request_path(request), method: :get, class: "btn-one", style: "border: none;" %>
    <%= button_to "DELETE", requests_path, method: :delete, class: "btn-two", data: { turbo_confirm: 'Are you sure you want to delete this booking?' } %>
  </div>
</div>

app/views/requests/edit.html.erb
<div class="m-3">
  <%# = turbo_frame_tag "request_#{@request.id}" do  %> <%# Couldnt redirect to the right page with the turbo_frame so removed it - Arno %>
  <div class="head-banner">
    <h1> Edit your request to <%= @request.carer.full_name %> </h1>
  </div>
    <%= simple_form_for(@request) do |f| %>
      <%= f.input :start_date, order: [:day, :month, :year] %>
      <%= f.input :end_date, order: [:day, :month, :year] %>
      <%= f.input :carers_home, collection: [["Carer's home", true], ["Pet's home", false]], prompt: 'Select status' %>
      <%= f.input :price %>
      <%= f.association :pet, collection: current_user.pets %>
      <%= f.submit :SAVE, class: "btn-one", style: "border: none;" %>
    <% end %>
  <%# end %>
    <div class="profile-buttons">
    <%= link_to 'CANCEL', requests_path, class: "btn-two", style: "width: 100%;" %>
  </div>
</div>

app/views/requests/index.html.erb
<div class='m-3'>
  <div class="head-banner">
    <h1 class="request-info">Upcoming Requests</h1>
  </div>
    <!-- My code starts here
    <% if @user.carer? %>
      <h6> Requests sent </h6>
      <% if @user_requests_sent.any?%>
        <% @user_requests_sent.each do |request| %>
          <%= render 'carer_request_sent', request: request %>
        <%end%>
      <% else %>
        <p class="default-message"><em>You haven't sent any request yet.</em></p>
      <% end %>
    <% end %>

   ends here-->

    <% if @user.carer? %> <%# carer view %> <!--YES:CARER-->
      <h6> Requests sent </h6>
      <% if @user_requests_sent_upcoming.any? %>
        <% @user_requests_sent_upcoming.each do |request| %>
           <%= render 'carer_request_sent', request: request %>
        <%end%>
        <% else %>
          <p class="default-message"><em>You haven't sent any request yet.</em></p>
        <% end %>

      <% if @upcoming_requests.empty? %><!--YES:CARER-->
        <h6>Requests Received </h6> <!--YES:CARER-->
        <p class="default-message"><em>You haven't received any request yet.</em></p>
        <% else %>
          <h6>Requests Received </h6> <!--YES:CARER-->
          <% @upcoming_requests.each do |request| %>
            <%= render 'upcoming_request_for_carer', request: request %>
          <% end %>
        <% end %>
      <br>
        <div class="head-banner">
          <h1 class="request-info">Past Requests</h1>
        </div>
        <% if @user_requests_sent_past.any? %>
          <% @user_requests_sent_past.each do |request| %>
            <div class="request-card">
              <%= render 'past_request_for_carer', request: request %>
            </div>
            <% end %>
          <% else %>
            <p class="default-message"><em>No past requests.</em></p>
          <% end %>
    <%end%>

    <% if @user.carer == false %> <%# user view %>
        <% if @upcoming_requests.empty? %>
          <p class="default-message"><em>No upcoming requests.</em></p>
          <% else %>
            <% @upcoming_requests.each do |request| %>
              <%= render 'upcoming_request_for_pet_owner', request: request %>
            <% end %>
          <% end %>
          <div class="head-banner">
            <h1 class="request-info">Past Requests</h1>
          </div>
          <% if @past_requests.empty? %>
            <p class="default-message"><em>No past requests.</em></p>
          <% else %>
            <% @past_requests.each do |request| %>
              <%= render 'past_request_for_pet_owner', request: request, carer: request.carer %>
            <% end %>
          <% end %>
    <% end %>
    <br>
    <br>
    <br>
</div>

app/views/requests/new.html.erb
<div class='m-3'>
  <div class="head-banner">
    <h1>Send a request</h1>
  </div>
  <%= simple_form_for [@carer, @request], url: carer_requests_path(@carer) do |f| %>
    <% if @request.errors.any? %>
      <% @request.errors.full_messages %>
    <% end %>
    <%= f.input :start_date, order: [:day, :month, :year] %>
    <%= f.input :end_date, order: [:day, :month, :year] %>
    <%= f.input :carers_home %>
    <%= f.input :price, label: "Price ($)" %>
    <%= f.association :pet, collection: current_user.pets %>
    <%= f.submit :BOOK, class: "btn-one", style: 'border: none;' %>
  <% end %>
  <div class="profile-buttons">
    <%= link_to 'BACK', carer_path(@carer), class: "btn-two", style: "width: 100%;" %>
  </div>
</div>